### PR TITLE
Update nightscout.go fork token auth

### PR DESCRIPTION
**Pull request by Freet128**

### CODE REVIEW

**Comment by Freet128** [comment]
I am not sure what the actual specifications would be but the openaps.readthedocs.io (https://bit.ly/2OtCNby) references the token as the "rigname-16character(hex?)" and oref0-setup.sh changes the API-SECRET in the crontab to API_SECRET=token=myrigname-27c914cabc506fa3.  I could definitely improve validation by checking for a "-" followed immediately by 16hex characters.

 I'll correct the format and string operations on the revised pull. Thanks for the feedback.

**Comment by PieterGit** [comment]
@Freet128 The regexp should be `^[a-z_0-9]{0,10}-[a-f0-9]{16}$`.
See https://github.com/nightscout/cgm-remote-monitor/blob/7c272ec67a7795e0f4edf7ff9abdfac1bd1308a0/lib/authorization/storage.js#L147-L149

**Comment by PieterGit** [comment]
@Freet128 
I think I fixed it with https://github.com/ecc1/nightscout/pull/4
Can't test with Dexcom now, will test later.

**Comment by PieterGit** [comment]
I think I fixed all @ecc1 remarks for the PR in https://github.com/ecc1/nightscout/pull/4 
I tested it and as far as I can see it's ok to go.
@Freet128 can you confirm that my PR also works for you?

**Comment by PieterGit** [comment]
I can confirm that token based authentication works. 
Integrated in master by @ecc1 with commit https://github.com/ecc1/nightscout/commit/3f979d4584317bc6ccebd1ee2f6fa815536a8f0d
See PR https://github.com/ecc1/nightscout/pull/4 for details.
This PR can be closed.

**Comment by Freet128** [comment]
Closing due to merge with other PR

**Pull request closed without merging**
