### PR TITLE
Support for token based authentication to the nightscout API's

### PR DESCRIPTION
**Pull request by PieterGit**
First attempt, need to figure out how to compile these go stuff and see if it works.

### CODE REVIEW

**Comment by PieterGit** [comment]
Update: I've been able to build my fork/PR from source. I think it should work for POST operations, but unfortunately it doesn't work for GET operations yet. Will look into it later. Not ready to merge yet.

**Comment by Freet128** [comment]
Thanks, I have been busy with my day job and couldn't contribute for the last few weeks.

**Comment by PieterGit** [comment]
Tested and works. I don't see raw data and `Found  calibration records.` but I think that's another issue.
@ecc1 Could you review and if ok, merge to master?

**Comment by ecc1** [comment]
When the NIGHTSCOUT_API_SECRET variable has the form "token=..." it will still be sent in the HTTP header as "api-secret=token=..." (in the addHeaders function).  Is that correct behavior?

Also, the regexp on line 142 will match an empty subjectName, like  "-0123456789abcdef". Is that correct?

Some style suggestions: use regexp.MustCompile and keep the result in a variable, rather than recompiling it and ignoring errors each time.  Then, test for a failed match and return, keeping the main behavior at the outer indentation level:

if !match {
  return ...
}
q := u.Query()
...

**Comment by PieterGit** [comment]
@ecc1  I changed the code. Answers to your questions:
- I changed the behaviour so that the api-secret won't be sent if used with token based authentication
- An empty subjectname, e.g. regexp of `-0123456789abcdef` is allowed in Nightscout. I'm thinking of changing the Nightscout behaviour, but I tested it and it works and is valid for current Nightscout <= 0.10.3
- implemented your style suggestions

I did quick testing of the token based. I want to do more testing and also test api-secret authentication later this week. If you more things that need to be addressed, feel free to comment and I will change them.

@Freet128 : if you can help test, please do

**Comment by PieterGit** [comment]
@ecc1 I tested with both token and API_SECRET and both work. I still see some problems with calibration records, but I don't think they are related to this PR.  Can you please review and merge if ok. If not ok, please let me know what needs to be done. Can you release a new version after the merge, so that I can integrate it into oref0?

**Comment by PieterGit** [comment]
I can confirm that token based authentication works. 
Integrated in master by @ecc1 with commit https://github.com/ecc1/nightscout/commit/3f979d4584317bc6ccebd1ee2f6fa815536a8f0d
Closing this PR

**Pull request closed without merging**
